name: Upload
run-name: ${{ github.actor }} is Uploading Apple association file
on: [push]
jobs:
  upload:
    name: Upload Apple association file
    runs-on: ubuntu-latest
    steps:
      - uses: MrFlynn/upload-to-netlify-action@v3
        with:
          source-file: "well-known/apple-developer-merchantid-domain-association"
          destination-path: "/.well-known/apple-developer-merchantid-domain-association"
          site-name: justjogging
          netlify-token: ${{ secrets.UPLOAD_FILE }}
